import {
  PDFDocument,
  PDFFont,
  PDFImage,
  PDFPage,
  rgb,
  StandardFonts,
} from "pdf-lib";

const PAGE_WIDTH = 595.28;
const PAGE_HEIGHT = 841.89;
const MARGIN = 40;
const CONTENT_WIDTH = PAGE_WIDTH - MARGIN * 2;
const PHOTO_SIZE = 64;
const MAX_TREES = 500;
const MAX_PHOTO_BYTES = 2 * 1024 * 1024;

const COLORS = {
  primary: rgb(0.31, 0.18, 0.61),
  dark: rgb(0.12, 0.12, 0.16),
  muted: rgb(0.38, 0.38, 0.43),
  light: rgb(0.95, 0.94, 0.98),
  border: rgb(0.84, 0.82, 0.9),
  white: rgb(1, 1, 1),
  green: rgb(0.1, 0.45, 0.28),
};

export interface SponsoredTree {
  id: string;
  species: string;
  plantedAt: string;
  location: string;
  annualCarbonKg: number;
  photoUrl?: string;
}

export interface ForestReportInput {
  sponsorName?: string;
  sponsorAddress?: string;
  trees: SponsoredTree[];
}

type Fetcher = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;

function isValidDate(value: string): boolean {
  return !Number.isNaN(Date.parse(value));
}

function isSafePhotoUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "https:";
  } catch {
    return false;
  }
}

export function validateForestReportInput(input: ForestReportInput): void {
  if (!input || !Array.isArray(input.trees)) {
    throw new Error("A trees array is required");
  }

  if (input.trees.length === 0) {
    throw new Error("At least one sponsored tree is required");
  }

  if (input.trees.length > MAX_TREES) {
    throw new Error(`A report can contain at most ${MAX_TREES} trees`);
  }

  for (const [index, tree] of input.trees.entries()) {
    if (!tree || typeof tree !== "object") {
      throw new Error(`Tree ${index + 1} is invalid`);
    }
    if (!tree.id.trim() || !tree.species.trim() || !tree.location.trim()) {
      throw new Error(`Tree ${index + 1} must include an id, species, and location`);
    }
    if (!isValidDate(tree.plantedAt)) {
      throw new Error(`Tree ${index + 1} has an invalid plantedAt date`);
    }
    if (!Number.isFinite(tree.annualCarbonKg) || tree.annualCarbonKg < 0) {
      throw new Error(`Tree ${index + 1} has an invalid annual carbon value`);
    }
    if (tree.photoUrl && !isSafePhotoUrl(tree.photoUrl)) {
      throw new Error(`Tree ${index + 1} photoUrl must be an HTTPS URL`);
    }
  }
}

function truncate(value: string, maxLength: number): string {
  return value.length <= maxLength ? value : `${value.slice(0, maxLength - 1)}…`;
}

function drawRightAligned(
  page: PDFPage,
  text: string,
  x: number,
  y: number,
  font: PDFFont,
  size: number,
  color = COLORS.dark
): void {
  page.drawText(text, {
    x: x - font.widthOfTextAtSize(text, size),
    y,
    font,
    size,
    color,
  });
}

function drawRule(page: PDFPage, y: number, color = COLORS.border): void {
  page.drawLine({
    start: { x: MARGIN, y },
    end: { x: PAGE_WIDTH - MARGIN, y },
    thickness: 1,
    color,
  });
}

async function loadPhoto(
  url: string,
  fetcher: Fetcher
): Promise<{ image: "png" | "jpg"; bytes: Uint8Array } | null> {
  try {
    const response = await fetcher(url, {
      headers: { Accept: "image/png,image/jpeg" },
    });
    if (!response.ok) return null;

    const contentLength = Number(response.headers.get("content-length") ?? 0);
    if (contentLength > MAX_PHOTO_BYTES) return null;

    const contentType = response.headers.get("content-type")?.split(";", 1)[0];
    if (contentType !== "image/png" && contentType !== "image/jpeg") return null;

    const bytes = new Uint8Array(await response.arrayBuffer());
    if (bytes.byteLength > MAX_PHOTO_BYTES) return null;
    return { image: contentType === "image/png" ? "png" : "jpg", bytes };
  } catch {
    return null;
  }
}

function drawHeader(page: PDFPage, fontBold: PDFFont, fontRegular: PDFFont): number {
  page.drawRectangle({
    x: 0,
    y: PAGE_HEIGHT - 92,
    width: PAGE_WIDTH,
    height: 92,
    color: COLORS.primary,
  });
  page.drawText("Azable", {
    x: MARGIN,
    y: PAGE_HEIGHT - 42,
    font: fontBold,
    size: 22,
    color: COLORS.white,
  });
  page.drawText("SPONSOR FOREST REPORT", {
    x: MARGIN,
    y: PAGE_HEIGHT - 64,
    font: fontRegular,
    size: 9,
    color: rgb(0.88, 0.84, 0.96),
  });
  return PAGE_HEIGHT - 124;
}

function drawFooter(page: PDFPage, fontRegular: PDFFont, pageNumber: number): void {
  page.drawRectangle({
    x: 0,
    y: 0,
    width: PAGE_WIDTH,
    height: 28,
    color: COLORS.light,
  });
  page.drawText("Generated by Azable", {
    x: MARGIN,
    y: 10,
    font: fontRegular,
    size: 7,
    color: COLORS.muted,
  });
  drawRightAligned(
    page,
    `Page ${pageNumber}`,
    PAGE_WIDTH - MARGIN,
    10,
    fontRegular,
    7,
    COLORS.muted
  );
}

export async function buildForestReportPdf(
  input: ForestReportInput,
  generatedAt = new Date(),
  fetcher: Fetcher = globalThis.fetch
): Promise<Uint8Array> {
  validateForestReportInput(input);

  const pdf = await PDFDocument.create();
  pdf.setTitle("Azable Sponsor Forest Report");
  pdf.setAuthor("Azable");
  pdf.setSubject("Sponsored trees, photos, and annual carbon summary");
  pdf.setCreationDate(generatedAt);

  const fontRegular = await pdf.embedFont(StandardFonts.Helvetica);
  const fontBold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const fontOblique = await pdf.embedFont(StandardFonts.HelveticaOblique);

  let pageNumber = 1;
  let page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  let cursor = drawHeader(page, fontBold, fontRegular);
  const sponsorLabel = input.sponsorName?.trim() || "Sponsor";
  const address = input.sponsorAddress?.trim();
  const totalCarbon = input.trees.reduce(
    (total, tree) => total + tree.annualCarbonKg,
    0
  );

  page.drawText(`${sponsorLabel}'s sponsored forest`, {
    x: MARGIN,
    y: cursor,
    font: fontBold,
    size: 16,
    color: COLORS.dark,
  });
  cursor -= 18;
  if (address) {
    page.drawText(truncate(address, 54), {
      x: MARGIN,
      y: cursor,
      font: fontRegular,
      size: 8,
      color: COLORS.muted,
    });
    cursor -= 14;
  }
  page.drawText(`Generated ${generatedAt.toISOString().slice(0, 10)}`, {
    x: MARGIN,
    y: cursor,
    font: fontOblique,
    size: 8,
    color: COLORS.muted,
  });
  cursor -= 28;

  const summaryY = cursor;
  const cardWidth = (CONTENT_WIDTH - 16) / 3;
  const summary = [
    ["Sponsored trees", String(input.trees.length)],
    ["Annual CO2 offset", `${totalCarbon.toFixed(2)} kg`],
    ["Species represented", String(new Set(input.trees.map((tree) => tree.species)).size)],
  ];
  summary.forEach(([label, value], index) => {
    const x = MARGIN + index * (cardWidth + 8);
    page.drawRectangle({
      x,
      y: summaryY - 48,
      width: cardWidth,
      height: 48,
      color: COLORS.light,
      borderColor: COLORS.border,
      borderWidth: 1,
    });
    page.drawText(label, {
      x: x + 10,
      y: summaryY - 18,
      font: fontRegular,
      size: 7,
      color: COLORS.muted,
    });
    page.drawText(value, {
      x: x + 10,
      y: summaryY - 37,
      font: fontBold,
      size: 12,
      color: COLORS.primary,
    });
  });
  cursor = summaryY - 78;

  drawRule(page, cursor);
  cursor -= 24;
  page.drawText("Sponsored trees", {
    x: MARGIN,
    y: cursor,
    font: fontBold,
    size: 12,
    color: COLORS.dark,
  });
  cursor -= 22;

  for (const tree of input.trees) {
    const rowHeight = 88;
    if (cursor - rowHeight < 52) {
      drawFooter(page, fontRegular, pageNumber);
      pageNumber += 1;
      page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
      cursor = drawHeader(page, fontBold, fontRegular) - 18;
      page.drawText("Sponsored trees (continued)", {
        x: MARGIN,
        y: cursor,
        font: fontBold,
        size: 12,
        color: COLORS.dark,
      });
      cursor -= 22;
    }

    page.drawRectangle({
      x: MARGIN,
      y: cursor - rowHeight + 8,
      width: CONTENT_WIDTH,
      height: rowHeight,
      color: COLORS.white,
      borderColor: COLORS.border,
      borderWidth: 1,
    });

    const photoX = PAGE_WIDTH - MARGIN - PHOTO_SIZE - 10;
    let textRight = photoX - 14;
    if (!tree.photoUrl) textRight = PAGE_WIDTH - MARGIN - 10;

    page.drawText(truncate(tree.species, 32), {
      x: MARGIN + 12,
      y: cursor - 18,
      font: fontBold,
      size: 11,
      color: COLORS.dark,
      maxWidth: Math.max(160, textRight - MARGIN - 12),
    });
    page.drawText(`Tree ID: ${truncate(tree.id, 30)}`, {
      x: MARGIN + 12,
      y: cursor - 34,
      font: fontRegular,
      size: 8,
      color: COLORS.muted,
    });
    page.drawText(`Location: ${truncate(tree.location, 42)}`, {
      x: MARGIN + 12,
      y: cursor - 48,
      font: fontRegular,
      size: 8,
      color: COLORS.muted,
      maxWidth: Math.max(160, textRight - MARGIN - 12),
    });
    page.drawText(`Planted: ${new Date(tree.plantedAt).toISOString().slice(0, 10)}`, {
      x: MARGIN + 12,
      y: cursor - 62,
      font: fontRegular,
      size: 8,
      color: COLORS.muted,
    });
    page.drawText(`${tree.annualCarbonKg.toFixed(2)} kg CO2 / year`, {
      x: MARGIN + 12,
      y: cursor - 76,
      font: fontBold,
      size: 8,
      color: COLORS.green,
    });

    if (tree.photoUrl) {
      const photo = await loadPhoto(tree.photoUrl, fetcher);
      if (photo) {
        const image: PDFImage =
          photo.image === "png"
            ? await pdf.embedPng(photo.bytes)
            : await pdf.embedJpg(photo.bytes);
        page.drawImage(image, {
          x: photoX,
          y: cursor - PHOTO_SIZE + 1,
          width: PHOTO_SIZE,
          height: PHOTO_SIZE,
        });
      } else {
        page.drawRectangle({
          x: photoX,
          y: cursor - PHOTO_SIZE + 1,
          width: PHOTO_SIZE,
          height: PHOTO_SIZE,
          color: COLORS.light,
          borderColor: COLORS.border,
          borderWidth: 1,
        });
        page.drawText("Photo\nunavailable", {
          x: photoX + 8,
          y: cursor - 32,
          font: fontRegular,
          size: 7,
          color: COLORS.muted,
          lineHeight: 10,
        });
      }
    }

    cursor -= rowHeight + 12;
  }

  drawFooter(page, fontRegular, pageNumber);
  return pdf.save();
}

export const forestReportLimits = {
  maxTrees: MAX_TREES,
  maxPhotoBytes: MAX_PHOTO_BYTES,
} as const;
